# Generated by Django 5.1.4 on 2026-07-09 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="标识"),
                ),
                ("title", models.CharField(max_length=160, verbose_name="名称")),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=200, verbose_name="副标题"),
                ),
                ("description", models.TextField(blank=True, verbose_name="简介")),
                (
                    "period",
                    models.CharField(blank=True, max_length=120, verbose_name="时期"),
                ),
                (
                    "language",
                    models.CharField(blank=True, max_length=80, verbose_name="语言"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "手稿集",
                "verbose_name_plural": "手稿集",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="ManuscriptPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(default=0, verbose_name="页码"),
                ),
                (
                    "image_name",
                    models.CharField(max_length=200, verbose_name="图片文件名"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="manuscripts/", verbose_name="手稿图片"
                    ),
                ),
                (
                    "transcription",
                    models.TextField(blank=True, verbose_name="官方转写"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="manuscripts.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "手稿页",
                "verbose_name_plural": "手稿页",
                "ordering": ["collection", "page_number"],
                "unique_together": {("collection", "image_name")},
            },
        ),
    ]
