# Generated by Django 5.1.4 on 2026-07-09 13:25

import django.db.models.deletion
import workspace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="名称")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="workspace.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作区文件夹",
                "verbose_name_plural": "工作区文件夹",
                "ordering": ["name"],
                "unique_together": {("owner", "parent", "name")},
            },
        ),
        migrations.CreateModel(
            name="UserImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=workspace.models.user_image_upload_to,
                        verbose_name="图片",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="原始文件名"
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(default=0, verbose_name="字节大小"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="workspace.folder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "工作区图片",
                "verbose_name_plural": "工作区图片",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Recognition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待识别"),
                            ("processing", "识别中"),
                            ("done", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="识别文本")),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="使用模型"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recognition",
                        to="workspace.userimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "识别结果",
                "verbose_name_plural": "识别结果",
            },
        ),
    ]
